marks = []

m1 = int(input("Enter marks of six students :"))
marks.append(m1)
m2 = int(input())
marks.append(m2)
m3 = int(input())
marks.append(m3)
m4 = int(input())
marks.append(m4)
m5 = int(input())
marks.append(m5)
m6 = int(input())
marks.append(m6)
marks.sort()
print("Marks of the students in sorted manner :",marks)
